version: "3.7"
services:
  api:
    build: .
    tty: true
    command: sh -c "npm install && npm run start:dev"
    ports:
      - "3000:3000"

    volumes:
      - type: bind
        source: .
        target: /myapp
  mysql:
    image: mysql/mysql-server:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: develop
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - /var/lib/mysql